Update installation_raspberry_pi_3B / 4B / 5B

diff --git a/installation_raspberry_pi_3b b/installation_raspberry_pi_3b
--- a/installation_raspberry_pi_3b
+++ b/installation_raspberry_pi_3b
@@ -1,7 +1,8 @@
-get the image https://github.com/aluminum-ice/pwnagotchi/releases/
+get the image https://github.com/aluminum-ice/pwnagotchi/releases/ #search 1.6.1
 burn with balena etcher
+========================================================================================================================
 before removing sd card, edit /boot/config.toml and change anything you need to in there
-
+========================================================================================================================
 main.name = "pwnagotchi"
  main.lang = "en"
  main.whitelist = [
@@ -20,23 +21,24 @@ main.name = "pwnagotchi"
  ui.display.enabled = true
  ui.display.type = "inky"
  ui.display.color = "black"
-
+==========================================================================================================================
 save and exit the file, unmount the disks
 put the microsd in the raspberry pi
 
 boot the pi with ethernet plugged in and your wlan usb adapter.
 
-ssh to it
+ssh to it #find the IP with IP SCANNER or something else if your 10.0.0.1 not working
 
  user: pi
  pass: raspberry 
-
+===========================================================================================================================
 upgrade everything
 
  $ sudo rm /var/lib/dpkg/status
  $ sudo touch /var/lib/dpkg/status
  $ sudo apt update
  $ sudo apt upgrade 
+ $ sudo raspi-config #set boot CLI automatic login pi user
 
 get the adafruit 3.5" tft working
 
@@ -45,44 +47,83 @@ $ sudo apt-get install apt-listchanges
 $ sudo apt-get install -y git python3-pip
 $ sudo apt-get --reinstall install python3-software-properties
 $ python3 -m pip install --upgrade pip
-$ pip3 install --upgrade adafruit-python-shell click
-$ git clone https://github.com/adafruit/Raspberry-Pi-Installer-Scripts.git
-$ cd Raspberry-Pi-Installer-Scripts
-
-I have the PiTFT 3.5" Resistive touchscreen so, i went with this, but you can find others here
-
-$ sudo python3 adafruit-pitft.py --display=35r --rotation=90 --install-type=console
-
-now get it working with pwnagotchi. ssh to your rpi. taken from here
 
 $ sudo /bin/bash 
 # cd /root
 # cp /usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/web/static/images/pwnagotchi.png /root 
 # apt install fbi 
+===========================================================================================================================
 # nano /etc/pwnagotchi/config.toml 
-
 add these or edit yours to be like this
 
-ui.display.enabled = true
-ui.display.type = "waveshare35lcd"
-ui.display.color = "black"
+# ui.display.enabled = true
+# ui.display.type = "waveshare35lcd" #for the waveshare 3.5" LCD
+# ui.display.color = "black"
 
 then edit the boot cmd line
 # nano /boot/cmdline.txt 
 add this if not already there 
 add "modules-load=dwc2,g_ether"
+========================================================================================================================
 then edit your rc.local
 # nano /etc/rc.local
-add this before exit 0 
-ln -s /root/pwnagotchi.png /tmp/pwnagotchi_1.png; ln -s /root/pwnagotchi.png /tmp/pwnagotchi_2.png; ln -s /root/pwnagotchi.png /tmp/pwnagotchi_3.png;
+#!/bin/sh -e
+#
+# rc.local
+#
+# This script is executed at the end of each multiuser runlevel.
+# Make sure that the script will "exit 0" on success or any other
+# value on error.
+#
+# In order to enable or disable this script just change the execution
+# bits.
+#
+# By default this script does nothing.
+
+# Print the IP address
+_IP=$(hostname -I) || true
+if [ "$_IP" ]; then
+  printf "My IP address is %s\n" "$_IP"
+fi
+
+ln -s /var/tmp/pwnagotchi/pwnagotchi.png /tmp/pwnagotchi_1.png
+ln -s /var/tmp/pwnagotchi/pwnagotchi.png /tmp/pwnagotchi_2.png
+ln -s /var/tmp/pwnagotchi/pwnagotchi.png /tmp/pwnagotchi_3.png
+
+exit 0
+========================================================================================================================
 then edit your /etc/profile
 # nano /etc/profile 
 add this at the end 
 . /home/pi/pwnagotchi.sh
+========================================================================================================================
 then edit your pwnagotchi configuration file
 # nano /home/pi/pwnagotchi.sh 
-#!/bin/bash 
-sudo fbi -T 1 -a -noverbose -t 15 -cachemem 0 /tmp/pwnagotchi_1.png /tmp/pwnagotchi_2.png /tmp/pwnagotchi_3.png &
+#!/bin/bash
+START=true
+
+while $START
+do
+  readarray -t PIDS < <(exec pgrep -x fbi)
+  if [[ ${#PIDS[@]} -eq 0 ]]; then
+    echo "No fbi process was found."
+    sudo fbi -T 1 -a -noverbose -t 5 -cachemem 0 /tmp/pwnagotchi_1.png /tmp/pwnagotchi_2.png /tmp/pwnagotchi_3.png
+  elif ps -fp "${PIDS[@]}" | fgrep -F '<defunct>' >/dev/null; then
+    echo "Defunct fbi process found: ${PIDS[*]}"
+    sudo kill -s SIGTERM "${PIDS[@]}"
+    sudo kill -s SIGKILL "${PIDS[@]}"
+  fi
+  sleep 15
+done
+==========================================================================================================================
 then make it executable
 # chmod +x /home/pi/pwnagotchi.sh 
+==========================================================================================================================
+For waveshare 3.5" LCD
+
+git clone https://github.com/waveshare/LCD-show.git
+cd LCD-show/
+chmod +x LCD35-show
+./LCD35-show
+
 you’re done. just reboot and you’re all set to start testing.
